"""Reaggregate BIOM reads with supplied full-ASV labels, then rebuild covariates.

Uses the original 0.80 rules in aggregate_full_asv_sintax.py and
taxonomy_association_sensitivity.py. SINTAX classifications themselves are
supplied inputs and are not generated by this script.
"""
import os
for key in ['OMP_NUM_THREADS','OPENBLAS_NUM_THREADS','MKL_NUM_THREADS','NUMEXPR_NUM_THREADS']:
    os.environ[key]='1'
import json
import time
import hashlib
import h5py
import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.sparse import csr_matrix, coo_matrix
from sklearn.decomposition import PCA
from core_paths import ROOT, DATA, OUT, PRIMARY, TAXONOMY_INPUT

started=time.perf_counter()
T=['Lacticaseibacillus','Lactobacillus','Leuconostoc','Limosilactobacillus','Ligilactobacillus','Pediococcus']
NUM=['age','bmi','antibiotic','ibd','ibs','year','depth_nonlab','energy','fiber_density','yogurt','plant_ferment','probiotic','nonlab_shannon','nonlab_logrichness']
REPLACED=['depth_nonlab','nonlab_shannon','nonlab_logrichness']
raw=pd.read_pickle(PRIMARY.parent/'agp_models/raw_predictors.pkl')
formal=raw.index[raw.total_reads_qc.ge(5000)]
ix=raw.index[raw.total_reads_qc.ge(5000)&raw.sex.isin(['female','male'])]
assert len(raw)==2877 and len(formal)==2760 and len(ix)==2748
original=pd.read_csv(PRIMARY/'association_covariate_design.tsv',sep='\t',dtype={'sample_id':str}).set_index('sample_id')
assert original.index.tolist()==ix.tolist()
biom=DATA/'输入/05_输入数据/01_原始输入/4168_ASV_table.biom'
with h5py.File(biom) as h:
    dec=lambda x:x.decode() if isinstance(x,bytes) else str(x)
    samples=[dec(x) for x in h['sample/ids'][:]]
    sequences=[dec(x) for x in h['observation/ids'][:]]
    matrix=h['observation/matrix']
    allmat=csr_matrix((matrix['data'][:],matrix['indices'][:],matrix['indptr'][:]),shape=(len(sequences),len(samples))).astype(np.int64)
mi=allmat[:,[samples.index(s) for s in ix]]
total=np.asarray(mi.sum(axis=0)).ravel()
assert np.array_equal(total,raw.loc[ix,'total_reads_qc'])
source=DATA/'输入/03_分析与结果/taxonomy_validation'
sequence_index=pd.read_csv(source/'asv_sequence_index.tsv',sep='\t')
assert sequence_index.asv_sequence.tolist()==sequences
reports=[]
for release in ['R07','R06']:
    labels_path=source/(release+'_all_asvs_genus_assignments.tsv')
    labels=pd.read_csv(labels_path,sep='\t').fillna({'genus':'','family':'','order':'','domain':''}).sort_values('biom_row')
    assert len(labels)==95567 and labels.biom_row.tolist()==list(range(95567))
    bacterial=labels.domain.eq('Bacteria') & labels.domain_bootstrap.ge(.8)
    forbidden=(labels['order'].eq('Lactobacillales') & labels.order_bootstrap.ge(.8)) | (labels.family.eq('Bifidobacteriaceae') & labels.family_bootstrap.ge(.8)) | (labels.genus.isin(T) & labels.genus_bootstrap.ge(.8))
    named=labels.genus.ne('') & ~labels.genus.str.contains('unclassified|uncultured',case=False,regex=True) & labels.genus_bootstrap.ge(.8)
    use=(bacterial & ~forbidden & named).to_numpy()
    families=labels.family.where(labels.family_bootstrap.ge(.8),'unclassified_family')
    feature_labels=('microbe::'+families+'|'+labels.genus).to_numpy()
    names=sorted(set(feature_labels[use])); lookup={name:j for j,name in enumerate(names)}
    selected=np.flatnonzero(use)
    incidence=coo_matrix((np.ones(len(selected),dtype=np.int64),([lookup[feature_labels[j]] for j in selected],selected)),shape=(len(names),len(labels))).tocsr()
    bg=pd.DataFrame((incidence@mi).T.toarray(),index=ix,columns=names)
    nonlab_depth=np.asarray(mi[(bacterial & ~forbidden).to_numpy()].sum(axis=0)).ravel()
    confident_bacterial=np.asarray(mi[bacterial.to_numpy()].sum(axis=0)).ravel()
    excluded=np.asarray(mi[(bacterial & forbidden).to_numpy()].sum(axis=0)).ravel()
    assert np.array_equal(confident_bacterial,excluded+nonlab_depth)
    assert np.all(nonlab_depth>=bg.sum(axis=1).to_numpy()) and (bg.sum(axis=1)>0).all()
    probs=bg.div(bg.sum(axis=1),axis=0)
    cov=raw.loc[ix,NUM+['sex','country','total_reads_qc']].copy()
    cov['depth_nonlab']=np.log10(1+nonlab_depth)
    cov['nonlab_shannon']=-(probs*np.log(probs.where(probs.gt(0),1))).sum(axis=1)
    cov['nonlab_logrichness']=np.log1p(bg.gt(0).sum(axis=1))
    medians=cov[NUM].median();num=cov[NUM].fillna(medians);sd=num.std(ddof=0)
    assert (sd>0).all()
    x=(num-num.mean())/sd
    x['bmi_missing']=cov.bmi.isna().astype(float)
    x['sex_male']=cov.sex.eq('male').astype(float)
    for country in ['US','UK','Unknown']:
        x['country_'+country]=cov.country.eq(country).astype(float)
    x=sm.add_constant(x)
    assert list(x.columns)==list(original.columns)
    unchanged=[column for column in x if column not in REPLACED]
    assert np.allclose(x[unchanged],original.loc[ix,unchanged],rtol=0,atol=2e-10)
    target={}
    for taxon in T:
        mask=(labels.genus.eq(taxon)&labels.genus_bootstrap.ge(.8)).to_numpy()
        assert not np.any(mask & use)
        target[taxon]=np.asarray(mi[mask].sum(axis=0)).ravel()
    target=pd.DataFrame(target,index=ix)
    keep=bg.gt(0).mean().ge(.1)
    rel=bg.loc[:,keep].div(bg.sum(axis=1),axis=0)
    lg=np.log(rel+.00005);clr=lg.sub(lg.mean(axis=1),axis=0)
    z=clr.sub(clr.mean()).div(clr.std(ddof=0))
    pca=PCA(n_components=10,svd_solver='full');scores=pca.fit_transform(z)
    scores=(scores-scores.mean(axis=0))/scores.std(axis=0,ddof=0)
    dest=TAXONOMY_INPUT/release;dest.mkdir(parents=True,exist_ok=True)
    x.to_csv(dest/'covariate_design.tsv',sep='\t')
    z.to_csv(dest/'standardized_clr.tsv.gz',sep='\t',compression={'method':'gzip','mtime':0})
    target.to_csv(dest/'target_counts.tsv',sep='\t')
    pd.DataFrame(scores,index=ix,columns=[f'PC{i+1:02d}' for i in range(10)]).to_csv(dest/'pc_scores.tsv',sep='\t')
    cov.to_csv(dest/'analysis_covariates.tsv',sep='\t')
    comparisons=[]
    for name in ['covariate_design.tsv','standardized_clr.tsv.gz','target_counts.tsv']:
        actual=pd.read_csv(dest/name,sep='\t',index_col=0)
        expected=pd.read_csv(source/'association_sensitivity'/release/name,sep='\t',index_col=0)
        assert actual.index.equals(expected.index) and actual.columns.equals(expected.columns)
        error=float(np.nanmax(np.abs(actual.to_numpy()-expected.to_numpy())))
        same=bool(np.allclose(actual,expected,rtol=1e-10,atol=1e-10,equal_nan=True))
        assert same,(release,name,error)
        comparisons.append(dict(file=name,shape=list(actual.shape),max_absolute_error=error,identifiers_and_columns_equal=True,numeric_equal=same))
    reports.append(dict(release=release,ASV_count=len(labels),participants=len(ix),n_background_genera=len(names),n_selected_genera=int(keep.sum()),PC_variance_explained=float(pca.explained_variance_ratio_.sum()),source_label_sha256=hashlib.sha256(labels_path.read_bytes()).hexdigest(),comparison=comparisons))
    print('TAXONOMY INPUTS REBUILT',release,'all',len(names),'selected',int(keep.sum()),comparisons,flush=True)
result=dict(status='pass',seconds=time.perf_counter()-started,scope='BIOM plus supplied full-ASV labels reaggregated, alternative target counts/background/design/CLR rebuilt. No new SINTAX classification.',BIOM_sha256=hashlib.sha256(biom.read_bytes()).hexdigest(),releases=reports)
(ROOT/'reports/core_taxonomy_input_rebuild.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf8')
